name: Deploy to Firebase Cloud Functions
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: cd functions && npm install

      # Menggunakan action resmi dari Firebase
      - name: Deploy to Firebase
        uses: FirebaseExtended/github-action@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
          # Perintah untuk deploy HANYA functions
          args: deploy --only functions
